### ISSUE TITLE
Pointless...?

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/ftb-rs-plus#1]
I'm not really seeing the point in this repository...

In your list of changes, you state that it:
* Fixes the bug related to / vs \, which he [already fixed](https://github.com/FTB-Gamepedia/ftb-rs/commit/a96af0a6a64ad22754491e84751ccc20fea94344) months ago
* And raises an error when it should, which is good, but it could just be PR'd into Peter's version. Or we could just continue to bother him about moving his repo to over here, since he did at one point say "I might get around to it eventually", or something.

@retep998 What do you think about moving your existing repo over here so that we can continue to contribute excellent rust to it?

@xbony2 What do you think about not having this repository since it is seemingly pointless?

**Comment by xbony2** [comment]
I can't be bothered to use retep's version; this is what works on my system, and has worked.
